services:
  db:

   image: postgres
   container_name: desafio_facilit_db
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "1234"
    POSTGRES_DB: "banco_dados_facilit"
   ports:
    - "5432:5432"
   volumes:
    - postgres_data:/var/lib/postgresql/data
  api:
   build: .
   container_name: desafio_facilit_api
   ports:
    - "8000:8000"
   volumes:
    - ./backend:/app/backend
   env_file:
    - .env
   depends_on:
    - db
  n8n:
   image: n8nio/n8n
   container_name: desafio_facilit_n8n
   ports:
    - "5678:5678"
   volumes:
    - n8n_data:/home/node/.n8n
   depends_on:
    - api
    - db
   environment:
    - GENERIC_TIMEZONE=America/Recife
   
volumes:
 postgres_data:
 n8n_data:
